{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
ARG BASE=docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

ARG docker_container_name
ARG image_version

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Update apt's cache of available packages
# Install required packages
RUN apt-get update   && \
    apt-get install -y  \
        logrotate       \
        gdb

{% if docker_ols_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_ols_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_ols_debs.split(' ')) }}
{%- endif %}

{% if docker_ols_whls.strip() %}
# Copy locally-built Python wheel dependencies
{{ copy_files("python-wheels/", docker_ols_whls.split(' '), "/python-wheels/") }}

# Install locally-built Python wheel dependencies
{{ install_python_wheels(docker_ols_whls.split(' ')) }}
{% endif %}

# Clean up
RUN apt-get clean -y      && \
    apt-get autoclean -y  && \
    apt-get autoremove -y && \
    rm -rf /debs ~/.cache /python-wheels

RUN mkdir -p /tmp/gnmic \
    && cd /tmp/gnmic \
    && curl -fsSL -o gnmic.deb https://github.com/openconfig/gnmic/releases/download/v0.41.0/gnmic_0.41.0_Linux_x86_64.deb \
    && dpkg -i gnmic.deb \
    && rm -rf /tmp/gnmic

COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["cli", "/cli/"]

ENTRYPOINT ["/usr/local/bin/supervisord"]
