# OTN-KVM Platform modules

OTN_KVM_OLSV_PLATFORM_MODULE_VERSION = 1.0
export OTN_KVM_OLSV_PLATFORM_MODULE_VERSION

OTN_KVM_OLSV_PLATFORM_MODULE = sonic-platform-otn-kvm-ols-v_$(OTN_KVM_OLSV_PLATFORM_MODULE_VERSION)_amd64.deb
$(OTN_KVM_OLSV_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-otn-kvm
$(OTN_KVM_OLSV_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(OTN_KVM_HALCLIENT_DEB)
$(OTN_KVM_OLSV_PLATFORM_MODULE)_PLATFORM = x86_64-otn-kvm_x86_64-r0

SONIC_DPKG_DEBS += $(OTN_KVM_OLSV_PLATFORM_MODULE)
