SONIC_EVENTD_OTN_PROFILE_VERSION = 1.0.0
export SONIC_EVENTD_OTN_PROFILE_VERSION

SONIC_EVENTD_OTN_PROFILE = sonic-eventd-otn-profile_$(SONIC_EVENTD_OTN_PROFILE_VERSION)_all.deb
$(SONIC_EVENTD_OTN_PROFILE)_SRC_PATH = $(PLATFORM_PATH)/sonic-eventd-otn-profile

SONIC_DPKG_DEBS += $(SONIC_EVENTD_OTN_PROFILE)
