OTN_KVM_THRIFT_ROOT_URL = https://raw.githubusercontent.com/sonic-molex/sonic-libmlx/refs/heads/main

OTN_KVM_THRIFT_LIB_DEB = libthrift_14_amd64.deb
$(OTN_KVM_THRIFT_LIB_DEB)_URL = "$(OTN_KVM_THRIFT_ROOT_URL)/$(OTN_KVM_THRIFT_LIB_DEB)"

OTN_KVM_THRIFT_LIB_DEV_DEB = libthrift-dev_14_amd64.deb
$(OTN_KVM_THRIFT_LIB_DEV_DEB)_URL = "$(OTN_KVM_THRIFT_ROOT_URL)/$(OTN_KVM_THRIFT_LIB_DEV_DEB)"

OTN_KVM_PYTHON3_SIX_DEB = python3-six_1.16.0-4_all.deb
$(OTN_KVM_PYTHON3_SIX_DEB)_URL = "$(OTN_KVM_THRIFT_ROOT_URL)/$(OTN_KVM_PYTHON3_SIX_DEB)"

OTN_KVM_THRIFT_PYTHON3_DEB = python3-thrift_14_amd64.deb
$(OTN_KVM_THRIFT_PYTHON3_DEB)_URL = "$(OTN_KVM_THRIFT_ROOT_URL)/$(OTN_KVM_THRIFT_PYTHON3_DEB)"

SONIC_ONLINE_DEBS += $(OTN_KVM_THRIFT_LIB_DEB) $(OTN_KVM_THRIFT_LIB_DEV_DEB) $(OTN_KVM_PYTHON3_SIX_DEB) $(OTN_KVM_THRIFT_PYTHON3_DEB)
