# docker image for ols

DOCKER_OLS_STEM = docker-ols
DOCKER_OLS = $(DOCKER_OLS_STEM).gz
DOCKER_OLS_DBG = $(DOCKER_OLS_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_OLS)_PATH = $(DOCKERS_PATH)/$(DOCKER_OLS_STEM)
#$(DOCKER_OLS)_PYTHON_WHEELS += $(SONIC_BGPCFGD) $(SONIC_FRR_MGMT_FRAMEWORK)

$(DOCKER_OLS)_DEPENDS += $(LIBYANG2) $(SONIC_OPTICAL_CONTROL) $(SONIC_TELEMETRY)
$(DOCKER_OLS)_INSTALL_DEBS = $(SONIC_OPTICAL_CONTROL) $(SONIC_TELEMETRY)
$(DOCKER_OLS)_DBG_DEPENDS = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_OLS)_DBG_DEPENDS += $(LIBSWSSCOMMON_DBG) $(LIBYANG2_DBG)

$(DOCKER_OLS)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_OLS)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_OLS)_VERSION = 1.0.0
$(DOCKER_OLS)_PACKAGE_NAME = ols

$(DOCKER_OLS)_SERVICE_REQUIRES = config-setup
$(DOCKER_OLS)_SERVICE_AFTER = swss syncd teamd
$(DOCKER_OLS)_SERVICE_BEFORE = ntp-config
$(DOCKER_OLS)_SERVICE_DEPENDENT_OF = swss

SONIC_DOCKER_IMAGES += $(DOCKER_OLS)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_OLS_DBG)

ifeq ($(INCLUDE_OLS), y)
ifeq ($(INSTALL_DEBUG_TOOLS), y)
SONIC_PACKAGES_LOCAL += $(DOCKER_OLS_DBG)
else
SONIC_PACKAGES_LOCAL += $(DOCKER_OLS)
endif
endif

$(DOCKER_OLS)_DEFAULT_FEATURE_STATE_ENABLED = y

$(DOCKER_OLS)_CONTAINER_NAME = ols
$(DOCKER_OLS)_CONTAINER_PRIVILEGED = true
$(DOCKER_OLS)_CONTAINER_VOLUMES += /etc/sonic:/etc/sonic:ro
$(DOCKER_OLS)_CONTAINER_VOLUMES += /usr/share/sonic/scripts:/usr/share/sonic/scripts:ro
$(DOCKER_OLS)_CONTAINER_TMPFS += /tmp/
$(DOCKER_OLS)_CONTAINER_TMPFS += /var/tmp/

$(DOCKER_OLS)_CLI_CONFIG_PLUGIN = /cli/config/plugins/config_ols.py
$(DOCKER_OLS)_CLI_SHOW_PLUGIN = /cli/show/plugins/show_ols.py
$(DOCKER_OLS)_CLI_CLEAR_PLUGIN = /cli/clear/plugins/clear_ols.py

SONIC_BOOKWORM_DOCKERS += $(DOCKER_OLS)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_OLS_DBG)
