# docker image for ot-orchagent

DOCKER_OT_ORCHAGENT_STEM = docker-ot-orchagent
DOCKER_OT_ORCHAGENT = $(DOCKER_OT_ORCHAGENT_STEM).gz
DOCKER_OT_ORCHAGENT_DBG = $(DOCKER_OT_ORCHAGENT_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_OT_ORCHAGENT)_DEPENDS += $(OTSS) $(SONIC_RSYSLOG_PLUGIN)

$(DOCKER_OT_ORCHAGENT)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_OT_ORCHAGENT)_DBG_DEPENDS +=   $(OTSS_DBG) \
                                $(LIBSWSSCOMMON_DBG) \
                                $(LIBOTAIREDIS_DBG) \
				$(SONIC_RSYSLOG_PLUGIN)

$(DOCKER_OT_ORCHAGENT)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

$(DOCKER_OT_ORCHAGENT)_PATH = $(DOCKERS_PATH)/$(DOCKER_OT_ORCHAGENT_STEM)

$(DOCKER_OT_ORCHAGENT)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_OT_ORCHAGENT)_VERSION = 1.0.0
$(DOCKER_OT_ORCHAGENT)_PACKAGE_NAME = otss

SONIC_DOCKER_IMAGES += $(DOCKER_OT_ORCHAGENT)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_OT_ORCHAGENT)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_OT_ORCHAGENT_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_OT_ORCHAGENT_DBG)

$(DOCKER_OT_ORCHAGENT)_CONTAINER_NAME = otss
$(DOCKER_OT_ORCHAGENT)_RUN_OPT += --privileged -t
$(DOCKER_OT_ORCHAGENT)_RUN_OPT += -v /etc/timezone:/etc/timezone:ro 
$(DOCKER_OT_ORCHAGENT)_RUN_OPT += -v /host/machine.conf:/host/machine.conf:ro
$(DOCKER_OT_ORCHAGENT)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_OT_ORCHAGENT)_RUN_OPT += -v /var/log/swss:/var/log/swss:rw

$(DOCKER_OT_ORCHAGENT)_BASE_IMAGE_FILES += swssloglevel:/usr/bin/swssloglevel
$(DOCKER_OT_ORCHAGENT)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
