# docker image for orchagent-ot

DOCKER_ORCHAGENT_OT_STEM = docker-orchagent-ot
DOCKER_ORCHAGENT_OT = $(DOCKER_ORCHAGENT_OT_STEM).gz
DOCKER_ORCHAGENT_OT_DBG = $(DOCKER_ORCHAGENT_OT_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_ORCHAGENT_OT)_DEPENDS += $(OTSS) $(SONIC_RSYSLOG_PLUGIN)

$(DOCKER_ORCHAGENT_OT)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_ORCHAGENT_OT)_DBG_DEPENDS +=   $(OTSS_DBG) \
                                $(LIBSWSSCOMMON_DBG) \
                                $(LIBOTAIREDIS_DBG) \
				$(SONIC_RSYSLOG_PLUGIN)

$(DOCKER_ORCHAGENT_OT)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

$(DOCKER_ORCHAGENT_OT)_PATH = $(DOCKERS_PATH)/$(DOCKER_ORCHAGENT_OT_STEM)

$(DOCKER_ORCHAGENT_OT)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_ORCHAGENT_OT)_VERSION = 1.0.0
$(DOCKER_ORCHAGENT_OT)_PACKAGE_NAME = otss

SONIC_DOCKER_IMAGES += $(DOCKER_ORCHAGENT_OT)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_ORCHAGENT_OT)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_ORCHAGENT_OT_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_ORCHAGENT_OT_DBG)

$(DOCKER_ORCHAGENT_OT)_CONTAINER_NAME = otss
$(DOCKER_ORCHAGENT_OT)_RUN_OPT += --privileged -t
$(DOCKER_ORCHAGENT_OT)_RUN_OPT += -v /etc/timezone:/etc/timezone:ro 
$(DOCKER_ORCHAGENT_OT)_RUN_OPT += -v /host/machine.conf:/host/machine.conf:ro
$(DOCKER_ORCHAGENT_OT)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_ORCHAGENT_OT)_RUN_OPT += -v /var/log/otss:/var/log/otss:rw

$(DOCKER_ORCHAGENT_OT)_BASE_IMAGE_FILES += otssloglevel:/usr/bin/otssloglevel
$(DOCKER_ORCHAGENT_OT)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
