# docker image for ols

DOCKER_OLS_STEM = docker-ols
DOCKER_OLS = $(DOCKER_OLS_STEM).gz
DOCKER_OLS_DBG = $(DOCKER_OLS_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_OLS)_PATH = $(DOCKERS_PATH)/$(DOCKER_OLS_STEM)
#$(DOCKER_OLS)_PYTHON_WHEELS += $(SONIC_BGPCFGD) $(SONIC_FRR_MGMT_FRAMEWORK)

$(DOCKER_OLS)_DEPENDS += $(SWSS) $(LIBYANG2) $(SONIC_OPTICAL_CONTROL)
$(DOCKER_OLS)_INSTALL_DEBS = $(SONIC_OPTICAL_CONTROL)
$(DOCKER_OLS)_DBG_DEPENDS = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_OLS)_DBG_DEPENDS += $(SWSS_DBG) $(LIBSWSSCOMMON_DBG) $(LIBYANG2_DBG)

$(DOCKER_OLS)_DBG_IMAGE_PACKAGES = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_OLS)_LOAD_DOCKERS += $(DOCKER_SWSS_LAYER_BOOKWORM)

$(DOCKER_OLS)_VERSION = 1.0.0
$(DOCKER_OLS)_PACKAGE_NAME = ols
$(DOCKER_OLS)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_OLS)_WARM_SHUTDOWN_AFTER = radv
$(DOCKER_OLS)_FAST_SHUTDOWN_BEFORE = swss
$(DOCKER_OLS)_FAST_SHUTDOWN_AFTER = radv

ifeq ($(INCLUDE_OLS), y)
SONIC_DOCKER_IMAGES += $(DOCKER_OLS)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_OLS)
endif

ifeq ($(INCLUDE_OLS), y)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_OLS_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_OLS_DBG)
endif

$(DOCKER_OLS)_CONTAINER_NAME = ols
$(DOCKER_OLS)_RUN_OPT += -t --cap-add=NET_ADMIN --cap-add=SYS_ADMIN
$(DOCKER_OLS)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_OLS)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro

$(DOCKER_OLS)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

SONIC_BOOKWORM_DOCKERS += $(DOCKER_OLS)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_OLS_DBG)
