# sonic-linecardsyncd (SONiC Chassis mgmt daemon) wheel package

SONIC_LINECARDSYNCD_PY3 = sonic_linecardsyncd-1.0-py3-none-any.whl
$(SONIC_LINECARDSYNCD_PY3)_SRC_PATH = $(SRC_PATH)/sonic-platform-daemons/sonic-linecardsyncd
$(SONIC_LINECARDSYNCD_PY3)_DEPENDS = $(SONIC_PY_COMMON_PY3) $(SONIC_PLATFORM_COMMON_PY3)
$(SONIC_LINECARDSYNCD_PY3)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(SONIC_LINECARDSYNCD_PY3)_PYTHON_VERSION = 3
SONIC_PYTHON_WHEELS += $(SONIC_LINECARDSYNCD_PY3)
