# sonic-pm (OTN PM daemon) Python wheel

ifeq ($(CONFIGURED_PLATFORM),otn-kvm)
SONIC_PM_PY3 = sonic_pm-1.0-py3-none-any.whl
$(SONIC_PM_PY3)_SRC_PATH = $(PLATFORM_PATH)/sonic-pm
$(SONIC_PM_PY3)_DEPENDS = $(SONIC_PY_COMMON_PY3)
$(SONIC_PM_PY3)_DEBS_DEPENDS = $(PYTHON3_SWSSCOMMON)
$(SONIC_PM_PY3)_PYTHON_VERSION = 3
$(SONIC_PM_PY3)_TEST = n
SONIC_PYTHON_WHEELS += $(SONIC_PM_PY3)
endif
