# Base docker build
FROM docker-syncd-ot-vs-sonic:latest

# Copy the cache data to host
From scratch as output
COPY --from=docker-syncd-ot-vs-sonic:latest /cache.tgz cache.tgz

# Clean up the cache data
FROM docker-syncd-ot-vs-sonic:latest as final
RUN rm /cache.tgz

