name: 202411-otn-kvm-build

on:
  push:
    branches: [ "202411_otn" ]
  pull_request:
    branches: [ "202411_otn" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: sonic-otn-server

    steps:
    - uses: actions/checkout@v4
      with:
        path: 202411_otn_${{github.run_number}}

    - name: build
      run: |
          cd 202411_otn_${{github.run_number}}
          make init
          make configure PLATFORM=ot-kvm
          make SONIC_BUILD_JOBS=8 target/sonic-otn-kvm.img.gz 

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: 202411-otn-artifact
        path: |
          202411_otn_${{github.run_number}}/sonic-installer.img
          202411_otn_${{github.run_number}}/target/*.img.gz
